config/routes.rb
Rails.application.routes.draw do
  root 'web/base#index'
  namespace :web, path: '/', as: "" do
    resources :players do
      collection do
        post :import
      end
    end
    resources :tournaments do
      collection do
        get :atp
        get :wta
        get :itf
        post :import
      end
    end
    resources :matches
  end
end

app/models/match.rb
# == Schema Information
#
# Table name: matches
#
#  id                   :uuid             not null, primary key
#  home_player_id       :uuid             not null
#  away_player_id       :uuid             not null
#  tournament_id        :uuid             not null
#  stage                :string           not null
#  date                 :date             not null
#  home_seed            :string
#  away_seed            :string
#  home_set_1_score     :integer
#  home_set_2_score     :integer
#  home_set_3_score     :integer
#  home_set_4_score     :integer
#  home_set_5_score     :integer
#  away_set_1_score     :integer
#  away_set_2_score     :integer
#  away_set_3_score     :integer
#  away_set_4_score     :integer
#  away_set_5_score     :integer
#  tiebreak_set_1_score :string
#  tiebreak_set_2_score :string
#  tiebreak_set_3_score :string
#  tiebreak_set_4_score :string
#  tiebreak_set_5_score :string
#  retirement           :boolean          default(FALSE)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

class Match < ApplicationRecord
  belongs_to :home_player, class_name: "Player"
  belongs_to :away_player, class_name: "Player"
  belongs_to :tournament

  validates :home_player_id, presence: { message: "Please specify participant of the match." }
  validates :away_player_id, presence: { message: "Please specify participant of the match." }
  validates :tournament_id, presence: { message: "Please specify tournament at which match has been played." }
  validates :stage, presence: { message: "Please specify stage of tournament." }
  validates :date, presence: { message: "Please specify date of the match." }
  validates_inclusion_of :stage, in: Tournaments::Enums::TournamentStages.values
  validates_numericality_of :home_set_1_score, :home_set_2_score, :home_set_3_score,
  :home_set_4_score, :home_set_5_score, :away_set_1_score, :away_set_2_score,
  :away_set_3_score, :away_set_4_score, :away_set_5_score,
  greater_than_or_equal_to: 0, less_than_or_equal_to: 7, allow_nil: true

  validates :home_set_1_score, :home_set_2_score, :away_set_1_score,
  :away_set_2_score, match_result_presence: true, unless: :retirement?

  validates_with MatchParticipantsValidator

  default_scope -> { order("created_at ASC") }

  def retirement?
    retirement
  end

  def brief_summary
    home_seed_string = home_seed.present? ? "[#{home_seed}] " : ""
    away_seed_string = away_seed.present? ? "[#{away_seed}] " : ""
    "[#{tournament.name} #{date.year} #{stage}] #{home_seed_string}#{home_player.full_name} v. #{away_seed_string}#{away_player.full_name}"
  end

  private

  def home_player_name
    home_player.full_name
  end

  def away_player_name
    away_player.full_name
  end

  def tournament_name
    tournament.name
  end
end

app/controllers/web/matches_controller.rb
class Web::MatchesController < Web::BaseController
  before_action :set_match, only: [:show, :update, :destroy]

  def index
    @matches = Paginator.call(Match.all, params[:page], params[:per_page])
    respond_to do |format|
      format.html
      format.csv do
         send_data(
           Matches::Export.call(Paginator.call(Match.all, params[:page], params[:per_page])),
           filename: "matches-#{Date.today}.csv")
      end
    end
  end

  def show
    @match = Matches::Decorators::Details.new(@match)
  end

  def new
    @form_utils = Matches::Facades::FormUtils.new
  end

  def create
    @form_utils = Matches::Facades::FormUtils.new
    @match = Match.new(match_params)
    if @match.save
      redirect_to @match, notice: 'Match was successfully created.'
    else
      flash[:alert] = @match.errors.values.flatten.join("<br>").html_safe
      render :new
    end
  end

  def edit
    @form_utils = Matches::Facades::FormUtils.new(Match.find(params[:id]))
  end

  def update
    @form_utils = Matches::Facades::FormUtils.new(Match.find(params[:id]))
    if @match.update(match_params)
      redirect_to @match, notice: 'Match was successfully updated.'
    else
      flash[:alert] = @match.errors.values.flatten.join("<br>").html_safe
      render :edit
    end
  end

  def destroy
    @match.destroy
    redirect_to matches_url, notice: 'Match has been deleted.'
  end

  private
  def set_match
    @match = Match.find(params[:id])
  end

  def match_params
    params.require(:match).permit(:home_player_id, :away_player_id,
      :tournament_id, :stage, :date, :home_seed, :away_seed, :home_set_1_score,
      :home_set_2_score, :home_set_3_score, :home_set_4_score, :home_set_5_score,
      :away_set_1_score, :away_set_2_score, :away_set_3_score, :away_set_4_score,
      :away_set_5_score, :tiebreak_set_1_score, :tiebreak_set_2_score,
      :tiebreak_set_3_score, :tiebreak_set_4_score, :tiebreak_set_5_score,
      :retirement)
  end
end

app/views/web/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>

<div class="row">
  <div class="col-1">
    <div class="form-group">
      <%= form.label :home_seed, 'Seed' %>
      <%= form.select :home_seed, @form_utils.seeds, { include_blank: true }, class: "form-control" %>
    </div>
  </div>

  <div class="col">
    <div class="form-group">
      <%= form.label :home_player_id, 'Player' %>
      <%= form.select :home_player_id, @form_utils.players, { include_blank: false }, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.label :home_set_1_score, 'Set 1' %>
      <%= form.number_field :home_set_1_score, min: 0, max: 7, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.label :home_set_2_score, 'Set 2' %>
      <%= form.number_field :home_set_2_score, min: 0, max: 7, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.label :home_set_3_score, 'Set 3' %>
      <%= form.number_field :home_set_3_score, min: 0, max: 7, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.label :home_set_4_score, 'Set 4' %>
      <%= form.number_field :home_set_4_score, min: 0, max: 7, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.label :home_set_5_score, 'Set 5' %>
      <%= form.number_field :home_set_5_score, min: 0, max: 7, class: "form-control" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-1">
    <div class="form-group">
      <%= form.select :away_seed, @form_utils.seeds, { include_blank: true }, class: "form-control" %>
    </div>
  </div>

  <div class="col">
    <div class="form-group">
      <%= form.select :away_player_id, @form_utils.players, { include_blank: false }, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.number_field :away_set_1_score, min: 0, max: 7, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.number_field :away_set_2_score, min: 0, max: 7, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.number_field :away_set_3_score, min: 0, max: 7, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.number_field :away_set_4_score, min: 0, max: 7, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.number_field :away_set_5_score, min: 0, max: 7, class: "form-control" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-2">
    <div class="form-check form-check-inline">
      <%= form.radio_button :retirement, true, class: "form-check-input" %>
      <%= form.label :retirement, class: "form-check-label" %>
    </div>
  </div>

  <div class="col-2 offset-3">
    <span class="align-middle">Tie-break scores</span>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.text_field :tiebreak_set_1_score, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.text_field :tiebreak_set_2_score, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.text_field :tiebreak_set_3_score, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.text_field :tiebreak_set_4_score, class: "form-control" %>
    </div>
  </div>

  <div class="col-1">
    <div class="form-group">
      <%= form.text_field :tiebreak_set_5_score, class: "form-control" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <div class="form-group">
      <%= form.label :tournament_id, 'Tournament' %>
      <%= form.select :tournament_id, @form_utils.tournaments, { include_blank: false }, class: "form-control" %>
    </div>
  </div>

  <div class="col">
    <div class="form-group">
      <%= form.label :stage %>
      <%= form.select :stage, @form_utils.stages, { include_blank: false }, class: "form-control" %>
    </div>
  </div>

  <div class="col">
    <div class="form-group">
      <%= form.label :date %>
      <%= form.date_field :date, value: @form_utils.date, class: "form-control" %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= form.submit class: "btn btn-primary", value: "Submit" %>
</div>
<% end %>

app/views/web/matches/edit.html.erb
<%= render 'shared/description', lead: "Edit #{@form_utils.lead_text}", description: nil %>

<%= render 'form', match: @form_utils.match %>

<%= link_to 'Show', @form_utils.match %> |
<%= link_to 'Back', matches_path %>

app/views/web/matches/index.html.erb
<%= render 'shared/description', lead: "Available matches in database", description: nil %>

<table class="table table-hover table-dark">
  <tbody>
    <% @matches.each_with_index do |match, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= match.brief_summary %></td>
      <td>
        <%= link_to 'More...', match_path(match), class: "btn btn-info btn-sm" %>
        <%= link_to 'Edit', edit_match_path(match), class: "btn btn-success btn-sm" %>
        <%= link_to 'Delete', match_path(match), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="row btn-group">
  <%= link_to 'Add match', new_match_path, class: "btn btn-success" %>
  <button class="btn btn-success" data-toggle="modal" data-target="#export-modal">
    Export to CSV
  </button>
</div>

<%= render 'shared/export_modal', data_type: "matches" %>
<%= render 'shared/paginator', collection: @matches %>

app/views/web/matches/new.html.erb
<%= render 'shared/description', lead: "Add new match", description: nil %>

<%= render 'form', match: @form_utils.match %>
<hr class="my-4">
<%= link_to 'Back', matches_path %>

app/views/web/matches/show.html.erb
<%= render 'shared/description', lead: "#{@match.summary_without_participants}", description: nil %>

<p>
  <%= @match.winner_player.full_name %> def. <%= @match.loser_player.full_name %> <%= @match.scoreline %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>