config/routes.rb
Rails.application.routes.draw do
  root 'web/base#index'
  namespace :web, path: '/', as: "" do
    resources :players do
      collection do
        post :import
      end
    end
    resources :tournaments do
      collection do
        get :atp
        get :wta
        get :itf
        post :import
      end
    end
    resources :matches
  end
end

app/views/shared/_description.html.erb
<p class="lead">
  <%= lead %>
</p>
<hr class="my-4">
<p>
  <%= description %>
</p>

app/views/shared/_export_modal.html.erb
<div class="modal fade" id="export-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Export data</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= link_to "Export all #{data_type} data", send("#{data_type}_path", { format: :csv, per_page: data_type.singularize.capitalize.constantize.count }), class: "btn btn-success" %>
        <%= link_to "Export just selected #{data_type} data", send("#{data_type}_path", { format: :csv, page: instance_variable_get("@#{data_type}").current_page }), class: "btn btn-success" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_import_modal.html.erb
<div class="modal fade" id="import-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Import data</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <%= form_for "#{data_type}", url: send("import_#{data_type}_path") do |f| %>
          <div class="form-group">
            <%= f.label :file, "Upload CSV File" %>
            <%= f.file_field :file, class: 'form-control-file', required: true %>
          </div>
          <%= f.submit class: "btn btn-primary", value: "Submit" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_paginator.html.erb
<%= paginate collection %>

app/views/shared/_web_main_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="main-menu">
  <a class="navbar-brand" href="<%= root_path %>" id="brand-link">Tennis matches</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path %>" id="index-link">Index</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= players_path %>" id="players-link">Players</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
          role="button" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          Tournaments
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= atp_tournaments_path %>" id="atp-tournaments-link">ATP</a>
          <a class="dropdown-item" href="<%= wta_tournaments_path %>" id="wta-tournaments-link">WTA</a>
          <a class="dropdown-item" href="<%= itf_tournaments_path %>" id="itf-tournaments-link">ITF</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%= tournaments_path %>" id="all-tournaments-link">See all list</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= matches_path %>" id="matches-link">Matches</a>
      </li>
    </ul>
  </div>
</nav>