config/routes.rb
Rails.application.routes.draw do
  root 'web/base#index'
  namespace :web, path: '/', as: "" do
    resources :players do
      collection do
        post :import
      end
    end
    resources :tournaments do
      collection do
        get :atp
        get :wta
        get :itf
        post :import
      end
    end
    resources :matches
  end
end

app/models/tournament.rb
# == Schema Information
#
# Table name: tournaments
#
#  id         :uuid             not null, primary key
#  name       :string           not null
#  country    :string           not null
#  city       :string           not null
#  category   :string           not null
#  tour       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tournament < ApplicationRecord
  has_many :matches
  validates :name, presence: { message: "Please specify name of the tournament." }
  validates :country, presence: { message: "Please specify host country of the tournament." }
  validates :city, presence: { message: "Please specify host city of the tournament." }
  validates :category, presence: { message: "Please select tournament's category." }
  validates :tour, presence: { message: "Please select tour."}
  validates_inclusion_of :tour, in: Tournaments::Enums::Tours.values
  validates_inclusion_of :category, in: Tournaments::Enums::WtaTournamentCategories.values, message: "Please select correct tournament category.", if: :wta_tournament?
  validates_inclusion_of :category, in: Tournaments::Enums::AtpTournamentCategories.values, message: "Please select correct tournament category.", if: :atp_tournament?
  validates_inclusion_of :category, in: Tournaments::Enums::ItfTournamentCategories.values, message: "Please select correct tournament category.", if: :itf_tournament?

  scope :itf_tournaments, -> { where(tour: Tournaments::Enums::Tours.itf) }
  scope :atp_tournaments, -> { where(tour: Tournaments::Enums::Tours.atp) }
  scope :wta_tournaments, -> { where(tour: Tournaments::Enums::Tours.wta) }

  def itf_tournament?
    tour == Tournaments::Enums::Tours.itf
  end

  def wta_tournament?
    tour == Tournaments::Enums::Tours.wta
  end

  def atp_tournament?
    tour == Tournaments::Enums::Tours.atp
  end
end

app/controllers/web/tournaments_controller.rb
class Web::TournamentsController < Web::BaseController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  def index
    @tournaments = Paginator.call(Tournament.all, params[:page], params[:per_page])
    respond_to do |format|
      format.html
      format.csv do
         send_data(
           Tournaments::Export.call(Paginator.call(Tournament.all, params[:page], params[:per_page])),
           filename: "tournaments-#{Date.today}.csv")
      end
    end
  end

  def atp
    @tournaments = Paginator.call(Tournament.atp_tournaments, params[:page], params[:per_page])
  end

  def wta
    @tournaments = Paginator.call(Tournament.wta_tournaments, params[:page], params[:per_page])
  end

  def itf
    @tournaments = Paginator.call(Tournament.itf_tournaments, params[:page], params[:per_page])
  end

  def new
    @form_utils = Tournaments::Facades::FormUtils.new(params[:tour])
  end

  def create
    @form_utils = Tournaments::Facades::FormUtils.new(tournament_params[:tour])
    @tournament = Tournament.new(tournament_params)
    if @tournament.save
      redirect_to @tournament, notice: 'Tournament was successfully created.'
    else
      flash[:alert] = @tournament.errors.values.flatten.join("<br>").html_safe
      render :new
    end
  end

  def edit
    @form_utils = Tournaments::Facades::FormUtils.new(@tournament.tour, @tournament)
  end

  def update
    @form_utils = Tournaments::Facades::FormUtils.new(@tournament.tour, @tournament)
    if @tournament.update(tournament_params)
      redirect_to @tournament, notice: 'Tournament was successfully updated.'
    else
      flash[:alert] = @tournament.errors.values.flatten.join("<br>").html_safe
      render :edit
    end
  end

  def destroy
    @tournament.destroy
    redirect_to send("#{@tournament.tour.downcase}_tournaments_url"), notice: "Tournament #{@tournament.name} has been deleted."
  end

  def import
    DataImporter.call(import_params[:file], :tournaments)
    redirect_to tournaments_path, notice: "Import success."
  end

  private
  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  def tournament_params
    params.require(:tournament).permit(:name, :country, :city, :category, :tour)
  end

  def import_params
    params.require(:tournaments).permit(:file)
  end
end

app/views/web/tournaments/_form.html.erb
<%= form_with model: tournament, local: true do |form| %>

<div class="row">
  <%= form.hidden_field :tour, value: tour %>

  <div class="col">
    <div class="form-group">
      <%= form.label :category %>
      <%= form.select :category, @form_utils.tournament_categories, { include_blank: false }, class: "form-control" %>
    </div>
  </div>

  <div class="col">
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, placeholder: "Name", class: "form-control" %>
    </div>
  </div>

  <div class="col">
    <div class="form-group">
      <%= form.label :country %>
      <%= form.select :country, Enums::Countries.list, { include_blank: false }, class: "form-control" %>
    </div>
  </div>

  <div class="col">
    <div class="form-group">
      <%= form.label :city %>
      <%= form.text_field :city, placeholder: "City", class: "form-control" %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= form.submit class: "btn btn-primary", value: "Submit" %>
</div>

<% end %>

app/views/web/tournaments/_list.html.erb
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Tour</th>
      <th scope="col">Category</th>
      <th scope="col">Name</th>
      <th scope="col">Country</th>
      <th scope="col">City</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% tournaments.each_with_index do |tournament, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= tournament.tour %></td>
        <td><%= tournament.category %></td>
        <td><%= tournament.name %></td>
        <td><%= tournament.country %></td>
        <td><%= tournament.city %></td>
        <td>
          <%= link_to 'More...', tournament, class: "btn btn-info btn-sm" %>
          <%= link_to 'Edit', edit_tournament_path(tournament, tour: tournament.tour), class: "btn btn-success btn-sm" %>
          <%= link_to 'Delete', tournament, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <% if tour %>
  <%= link_to 'Add tournament', new_tournament_path(tour: tour), class: "btn btn-success" %>
  <% else %>
  <div class="btn-group">
    <%= link_to 'Add WTA tournament', new_tournament_path(tour: "WTA"), class: "btn btn-success" %>
    <%= link_to 'Add ATP tournament', new_tournament_path(tour: "ATP"), class: "btn btn-success" %>
    <%= link_to 'Add ITF tournament', new_tournament_path(tour: "ITF"), class: "btn btn-success" %>
    <button class="btn btn-success" data-toggle="modal" data-target="#export-modal">
      Export to CSV
    </button>
    <button class="btn btn-success" data-toggle="modal" data-target="#import-modal">
      Import from CSV
    </button>
  </div>
  <% end %>
</div>

<%= render 'shared/export_modal', data_type: "tournaments" %>
<%= render 'shared/import_modal', data_type: "tournaments" %>
<%= render 'shared/paginator', collection: tournaments %>

app/views/web/tournaments/atp.html.erb
<%= render 'shared/description', lead: "List of ATP tournaments in database", description: nil %>

<%= render 'list', tournaments: @tournaments, tour: "ATP" %>

app/views/web/tournaments/edit.html.erb
<%= render 'shared/description', lead: "Edit #{@form_utils.tournament.name} tournament", description: nil %>

<%= render 'form', tournament: @form_utils.tournament, tour: @form_utils.tour %>
<hr class="my-4">
<%= link_to 'Show', @form_utils.tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/web/tournaments/index.html.erb
<%= render 'shared/description', lead: "List of all tournaments in database", description: nil %>

<%= render 'list', tournaments: @tournaments, tour: nil %>

app/views/web/tournaments/itf.html.erb
<%= render 'shared/description', lead: "List of ITF tournaments in database", description: nil %>

<%= render 'list', tournaments: @tournaments, tour: "ITF" %>

app/views/web/tournaments/new.html.erb
<%= render 'shared/description', lead: "Add new #{@form_utils.tour} tournament", description: nil %>

<%= render 'form', tournament: @form_utils.tournament, tour: @form_utils.tour %>
<hr class="my-4">
<%= link_to 'Back', tournaments_path %>

app/views/web/tournaments/show.html.erb
<%= render 'shared/description', lead: "Details about #{@tournament.name} tournament", description: nil %>

<p>
  <strong>Name:</strong>
  <%= @tournament.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @tournament.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @tournament.city %>
</p>

<p>
  <strong>Category:</strong>
  <%= @tournament.category %>
</p>

<p>
  <strong>Tour:</strong>
  <%= @tournament.tour %>
</p>

<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>

app/views/web/tournaments/wta.html.erb
<%= render 'shared/description', lead: "List of WTA tournaments in database", description: nil %>

<%= render 'list', tournaments: @tournaments, tour: "WTA" %>