config/routes.rb
Rails.application.routes.draw do
  root 'web/base#index'
  namespace :web, path: '/', as: "" do
    resources :players do
      collection do
        post :import
      end
    end
    resources :tournaments do
      collection do
        get :atp
        get :wta
        get :itf
        post :import
      end
    end
    resources :matches
  end
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id            :uuid             not null, primary key
#  first_name    :string           not null
#  last_name     :string           not null
#  country       :string           not null
#  date_of_birth :date
#  born          :string
#  sex           :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Player < ApplicationRecord
  has_many :home_matches, class_name: "Match", foreign_key: "home_player_id"
  has_many :away_matches, class_name: "Match", foreign_key: "away_player_id"

  validates :first_name, presence: { message: "Please specify player's first name." }
  validates :last_name, presence: { message: "Please specify player's last name." }
  validates :country, presence: { message: "Please specify player's nationality." }
  validates :sex, presence: { message: "Please specify player's sex." }
  validates_inclusion_of :sex, in: ["female", "male"]

  default_scope -> { order("created_at ASC") }

  def age
    ((Time.current - date_of_birth.to_time) / 1.year.seconds).floor
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def full_date_of_birth
    date_of_birth.strftime("%-d %B %Y")
  end
end

app/controllers/web/players_controller.rb
class Web::PlayersController < Web::BaseController
  before_action :set_player, except: [:index, :new, :create, :import]

  def index
    @players = Paginator.call(Player.all, params[:page], params[:per_page])
    respond_to do |format|
      format.html
      format.csv do
         send_data(
           Players::Export.call(Paginator.call(Player.all, params[:page], params[:per_page])),
           filename: "players-#{Date.today}.csv")
      end
    end
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to player_path(@player), notice: "Player has been created successfully."
    else
      flash[:alert] = @player.errors.values.flatten.join("<br>").html_safe
      render :new
    end
  end

  def update
    if @player.update(player_params)
      redirect_to player_path(@player), notice: "Player has been updated successfully."
    else
      flash[:alert] = @player.errors.values.flatten.join("<br>").html_safe
      render :edit
    end
  end

  def destroy
    @player.destroy
    redirect_to players_path, notice: "Player #{@player.full_name} has been deleted."
  end

  def import
    DataImporter.call(import_params[:file], :players)
    redirect_to players_path, notice: "Import success."
  end

  private
  def player_params
    params.require(:player).permit(:first_name, :last_name, :date_of_birth,
      :country, :born, :sex)
  end

  def import_params
    params.require(:players).permit(:file)
  end

  def set_player
    @player = Player.find(params[:id])
  end
end

app/views/web/players/_form.html.erb
<%= form_with model: player, local: true do |f| %>

<div class="row">
  <div class="col">
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, placeholder: "First name", class: "form-control" %>
    </div>
  </div>

  <div class="col">
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, placeholder: "Last name", class: "form-control" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <div class="form-group">
      <%= f.label :date_of_birth %>
      <%= f.date_field :date_of_birth, class: "form-control" %>
    </div>
  </div>

  <div class="col">
    <div class="form-group">
      <%= f.label :born %>
      <%= f.text_field :born, placeholder: "Born", class: "form-control" %>
    </div>
  </div>

  <div class="col">
    <div class="form-group">
      <%= f.label :country %>
      <%= f.select :country, Enums::Countries.list, { include_blank: false }, class: "form-control" %>
    </div>
  </div>

  <div class="col">
    <div class="form-check form-check-inline">
      <%= f.radio_button :sex, "male", class: "form-check-input" %>
      <%= f.label :male, class: "form-check-label" %>
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :sex, "female", class: "form-check-input" %>
      <%= f.label :female, class: "form-check-label" %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.submit class: "btn btn-primary", value: "Submit" %>
</div>

<% end %>

app/views/web/players/edit.html.erb
<%= render 'shared/description', lead: "Edit details about #{@player.full_name}", description: nil %>

<%= render 'form', player: @player %>
<hr class="my-4">
<%= link_to 'Back', players_path %>

app/views/web/players/index.html.erb
<%= render 'shared/description', lead: "List of tennis players in database", description: nil %>

<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Date of birth</th>
      <th scope="col">Born</th>
      <th scope="col">Nationality</th>
      <th scope="col">Age</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @players.each_with_index do |player, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= player.first_name %></td>
      <td><%= player.last_name %></td>
      <td><%= player.full_date_of_birth %></td>
      <td><%= player.born %></td>
      <td><%= player.country %></td>
      <td><%= player.age %></td>
      <td>
        <%= link_to 'More...', player_path(player), class: "btn btn-info btn-sm" %>
        <%= link_to 'Edit', edit_player_path(player), class: "btn btn-success btn-sm" %>
        <%= link_to 'Delete', player_path(player), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="row btn-group">
  <%= link_to 'Add player', new_player_path, class: "btn btn-success" %>
  <button class="btn btn-success" data-toggle="modal" data-target="#export-modal">
    Export to CSV
  </button>
  <button class="btn btn-success" data-toggle="modal" data-target="#import-modal">
    Import from CSV
  </button>
</div>

<%= render 'shared/export_modal', data_type: "players" %>
<%= render 'shared/import_modal', data_type: "players" %>
<%= render 'shared/paginator', collection: @players %>

app/views/web/players/new.html.erb
<%= render 'shared/description', lead: "Add new tennis player", description: nil %>

<%= render 'form', player: @player %>
<hr class="my-4">
<%= link_to 'Back', players_path %>

app/views/web/players/show.html.erb
<%= render 'shared/description', lead: @player.full_name, description: nil %>

<p>
  <strong>Born: </strong><%= @player.full_date_of_birth %> (age <%= @player.age %>)
</p>
<p>
  <strong>Nationality: </strong><%= @player.country %>
</p>

<hr class="my-4">
<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>